packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - sharp
  - unrs-resolver
