export { MigrationLoader } from './core/loader'
export { Migrator } from './core/migrator'
export { CURRENT_CONFIG_VERSION, findMigrationPath, getAvailableMigrations, MIGRATION_REGISTRY } from './core/registry'
export { StructuredMigrationProcessor } from './processors/structured-processor'
export * from './types'
export { MigrationDetector } from './utils/detector'
